python GetCode.py --idx 1
python GetCode.py --idx 2
python GetCode.py --idx 3
python GetCode.py --idx 4
python GetCode.py --idx 5
python GetCode.py --idx 6
python GetCode.py --idx 7
python GetCode.py --idx 8
python GetCode.py --idx 9
python GetCode.py --idx 10
python GetCode.py --idx 11
python GetCode.py --idx 12
python GetCode.py --idx 13
python GetCode.py --idx 14
python GetCode.py --idx 15
python GetCode.py --idx 16
python GetCode.py --idx 17
python GetCode.py --idx 18
python GetCode.py --idx 19
python GetCode.py --idx 20
python GetCode.py --idx 21
python GetCode.py --idx 22
python GetCode.py --idx 23
python GetCode.py --idx 24
python GetCode.py --idx 25
python GetCode.py --idx 26
python GetCode.py --idx 27
python GetCode.py --idx 28
python GetCode.py --idx 29
python GetCode.py --idx 30
python GetCode.py --idx 31
python GetCode.py --idx 32
python GetCode.py --idx 33
python GetCode.py --idx 34
python GetCode.py --idx 35
python GetCode.py --idx 36
python GetCode.py --idx 37
python GetCode.py --idx 38
python GetCode.py --idx 39
python GetCode.py --idx 40
python GetCode.py --idx 41
python GetCode.py --idx 42
python GetCode.py --idx 43
python GetCode.py --idx 44
python GetCode.py --idx 45
python GetCode.py --idx 46
python GetCode.py --idx 47
python GetCode.py --idx 48
python GetCode.py --idx 49
python GetCode.py --idx 50
python GetCode.py --idx 51
python GetCode.py --idx 52
python GetCode.py --idx 53
python GetCode.py --idx 54
python GetCode.py --idx 55
python GetCode.py --idx 56
python GetCode.py --idx 57
python GetCode.py --idx 58
python GetCode.py --idx 59
python GetCode.py --idx 60
python GetCode.py --idx 61
python GetCode.py --idx 62
python GetCode.py --idx 63
python GetCode.py --idx 64
python GetCode.py --idx 65
python GetCode.py --idx 66
python GetCode.py --idx 67
python GetCode.py --idx 68
python GetCode.py --idx 69
python GetCode.py --idx 70
python GetCode.py --idx 71
python GetCode.py --idx 72
python GetCode.py --idx 73
python GetCode.py --idx 74
python GetCode.py --idx 75
python GetCode.py --idx 76
python GetCode.py --idx 77
python GetCode.py --idx 78
python GetCode.py --idx 79
python GetCode.py --idx 80
python GetCode.py --idx 81
python GetCode.py --idx 82
python GetCode.py --idx 83
python GetCode.py --idx 84
python GetCode.py --idx 85
python GetCode.py --idx 86
python GetCode.py --idx 87
python GetCode.py --idx 88
python GetCode.py --idx 89
python GetCode.py --idx 90
python GetCode.py --idx 91
python GetCode.py --idx 92
python GetCode.py --idx 93
python GetCode.py --idx 94
python GetCode.py --idx 95
python GetCode.py --idx 96
python GetCode.py --idx 97
python GetCode.py --idx 98
python GetCode.py --idx 99
python GetCode.py --idx 100
python GetCode.py --idx 101
python GetCode.py --idx 102
python GetCode.py --idx 103
python GetCode.py --idx 104
python GetCode.py --idx 105
python GetCode.py --idx 106
python GetCode.py --idx 107
python GetCode.py --idx 108
python GetCode.py --idx 109
python GetCode.py --idx 110
python GetCode.py --idx 111
python GetCode.py --idx 112
python GetCode.py --idx 113
python GetCode.py --idx 114
python GetCode.py --idx 115
python GetCode.py --idx 116
python GetCode.py --idx 117
python GetCode.py --idx 118
python GetCode.py --idx 119
python GetCode.py --idx 120
python GetCode.py --idx 121
python GetCode.py --idx 122
python GetCode.py --idx 123
python GetCode.py --idx 124
python GetCode.py --idx 125
python GetCode.py --idx 126
python GetCode.py --idx 127
python GetCode.py --idx 128
python GetCode.py --idx 129
python GetCode.py --idx 130
python GetCode.py --idx 131
python GetCode.py --idx 132
python GetCode.py --idx 133
python GetCode.py --idx 134
python GetCode.py --idx 135
python GetCode.py --idx 136
python GetCode.py --idx 137
python GetCode.py --idx 138
python GetCode.py --idx 139
python GetCode.py --idx 140
python GetCode.py --idx 141
python GetCode.py --idx 142
python GetCode.py --idx 143
python GetCode.py --idx 144
python GetCode.py --idx 145
python GetCode.py --idx 146
python GetCode.py --idx 147
python GetCode.py --idx 148
python GetCode.py --idx 149
python GetCode.py --idx 150
python GetCode.py --idx 151
python GetCode.py --idx 152
python GetCode.py --idx 153
python GetCode.py --idx 154
python GetCode.py --idx 155
python GetCode.py --idx 156
python GetCode.py --idx 157
python GetCode.py --idx 158
python GetCode.py --idx 159
python GetCode.py --idx 160
python GetCode.py --idx 161
python GetCode.py --idx 162
python GetCode.py --idx 163
python GetCode.py --idx 164
python GetCode.py --idx 165
python GetCode.py --idx 166
python GetCode.py --idx 167
python GetCode.py --idx 168
python GetCode.py --idx 169
python GetCode.py --idx 170
python GetCode.py --idx 171
python GetCode.py --idx 172
python GetCode.py --idx 173
python GetCode.py --idx 174
python GetCode.py --idx 175
python GetCode.py --idx 176 
python GetCode.py --idx 177
python GetCode.py --idx 178
python GetCode.py --idx 179
python GetCode.py --idx 180
python GetCode.py --idx 181
python GetCode.py --idx 182
python GetCode.py --idx 183
python GetCode.py --idx 184
python GetCode.py --idx 185
python GetCode.py --idx 186
python GetCode.py --idx 187
python GetCode.py --idx 188
python GetCode.py --idx 189
python GetCode.py --idx 190
python GetCode.py --idx 191
python GetCode.py --idx 192
python GetCode.py --idx 193
python GetCode.py --idx 194
python GetCode.py --idx 195
python GetCode.py --idx 196
python GetCode.py --idx 197
python GetCode.py --idx 198
python GetCode.py --idx 199
python GetCode.py --idx 200
